jira-backup: Write sha1 checksum to own file
As per backup design document

diff --git a/atlassian/jira/bin/jira-backup b/atlassian/jira/bin/jira-backup
--- a/atlassian/jira/bin/jira-backup
+++ b/atlassian/jira/bin/jira-backup
@@ -113,8 +113,15 @@ function create_archive
     cd $BACKUP_HOME_DIR && tar czf $ARCHIVE_NAME $BACKUP_NAME/ || return $?
     
     local size=`stat -c%s $BACKUP_HOME_DIR/$ARCHIVE_NAME`
-    local checksum=`sha1sum $BACKUP_HOME_DIR/$ARCHIVE_NAME | cut -d ' ' -f 1`
-    notify "Created tar archive '$BACKUP_HOME_DIR/$ARCHIVE_NAME', size: $size bytes, SHA1: $checksum"
+    notify "Created backup archive '$BACKUP_HOME_DIR/$ARCHIVE_NAME', size: $size bytes"
+}
+
+function calculate_checksum
+{
+    sha1sum $BACKUP_HOME_DIR/$ARCHIVE_NAME > $BACKUP_HOME_DIR/$ARCHIVE_NAME.sha1
+
+    local checksum=`cut -d ' ' -f 1 $BACKUP_HOME_DIR/$ARCHIVE_NAME.sha1`
+    notify "Checksum of backup archive '$BACKUP_HOME_DIR/$ARCHIVE_NAME': $checksum"
 }
 
 function remove_work_directory
@@ -135,5 +142,7 @@ copy_application_data || fail_and_cleanup "Could not copy application data"
 bind_application_version || fail_and_cleanup "Could not bind application version (wtf?)"
 
 create_archive || fail_and_cleanup "Could not create archive"
+
+calculate_checksum || fail "Backup created but could not calculate checksum"
 
 remove_work_directory || fail "Backup created but could not remove work directory"
